apiVersion: v1
kind: ConfigMap
metadata:
  name: landslide-ml-config
data:
  LOG_LEVEL: "INFO"
  PREDICTION_INTERVAL: "180"
---
apiVersion: v1
kind: Service
metadata:
  name: landslide-ml-metrics
  labels:
    app: landslide-ml-app
spec:
  selector:
    app: landslide-ml-app
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
      name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landslide-ml-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: landslide-ml.your-domain.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landslide-ml-service
            port:
              number: 80 