apiVersion: batch/v1
kind: CronJob
metadata:
  name: landslide-prediction-job
spec:
  schedule: "*/3 * * * *"  # Every 3 minutes
  concurrencyPolicy: Forbid  # Don't run if previous job is still running
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: landslide-prediction
            image: your-registry/landslide-ml-app:latest
            command: ["python", "-c", "import landslide_prediction; landslide_prediction.main()"]
            env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: SUPABASE_URL
              value: "https://axhllqkehjppzhjyjumg.supabase.co"
            - name: SUPABASE_KEY
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4aGxscWtlaGpwcHpoanlqdW1nIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjIxODAxNCwiZXhwIjoyMDY3Nzk0MDE0fQ.m8Ye09Nt7pZf4cIdIQpNoC0hMzJXHl83KoiLgUSXy4A"
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            volumeMounts:
            - name: app-logs
              mountPath: /app/logs
          volumes:
          - name: app-logs
            emptyDir: {}
          restartPolicy: OnFailure 